target-version = "py38"

[lint]
select = ["ALL"]
ignore = ["D", "T", "COM812"]

[lint.per-file-ignores]
"contrib/wheels/build_wheel.py" = ["S603"]
"scripts/*" = ["S603"]
"tests/python/test_*" = ["S101"]
